channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - tqdm
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - jupyter
  - ipywidgets
  - statsmodels
#  - pip:
#      - crowd-kit
